version: '3.5'

services:
    shepherd:
        image: oldwebtoday/shepherd:1.1.0-dev
        command: python -u main.py
        environment:
            - BROWSER_NET=oldweb-today_browsers
            - PROXY_HOST=pywb

        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./flocks:/app/flocks
            - ./main.py:/app/main.py
            - ./pool_config.yaml:/app/pool_config.yaml
            - ./templates/:/app/shepherd/templates/
            - ./static/:/app/shepherd/static/

        ports:
            - 9020:9020

    redis:
        image: redis:3.2.4
        networks:
          - browsers
          - default

    pywb:
        build: ./pywb
        image: oldwebtoday/pywb
        networks:
          - browsers

        environment:
          - REDIS_URL=redis://redis/0

        ports:
            - 8080:8080

networks:
    default:
        driver: bridge

    browsers:
        driver: bridge



